name: 'Sensitivity'
description: 'Detect sensitive information inside code changes'
author: 'Jeroen Vannevel'
inputs:
  path:
    required: true
    description: 'The path to your root folder, e.g. src'
  ignorePaths:
    required: false
    description: 'Optional: globs that will be ignored'
runs:
  using: 'node12'
  main: 'dist/index.js'
