name: 'Sensitive Data Check'
description: 'Detect sensitive information inside code changes'
author: 'Jeroen Vannevel'
inputs:
  path:
    required: true
    description: 'The path to your root folder, e.g. src'
  token:
    required: true
    description: 'Github authentication token, i.e. secrets.GITHUB_TOKEN'
  ignorePaths:
    required: false
    description: 'Optional: globs that will be ignored'
  ignoreEmails:
    required: false
    description: 'Optional: email patterns that will be ignored (regex)'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'eye'  
  color: 'blue'
